"""Context summarisation cap (Phase 2.A.4).

When the predicted ``prompt_tokens`` for the next turn exceed
``CAP_FRACTION * ctx_window`` we collapse old messages into a single
``system: "[summary] ..."`` block, leaving the most recent ``KEEP_TAIL``
messages untouched.

Idempotency
-----------
The summary block is tagged with ``[summary v{N}]`` at the start of its
content. On subsequent turns:
- if the existing summary block is the only "old" content -> we leave it
  alone (no infinite resummary loop);
- if new old messages have piled up -> we *extend* the summary with a
  second-pass call covering "previous summary + new old messages".

The actual summary text is generated by ``runtime.chat_summary`` (a small
non-streaming wrapper). When it fails (offline / model error) we fall
back to a lossy truncation: keep the first system message + tail.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Callable

logger = logging.getLogger(__name__)

CAP_FRACTION = 0.85
KEEP_TAIL = 10  # how many recent messages to leave intact (excl. last system)
SUMMARY_PROMPT = (
    "Summarise the following conversation between a user and an AI coding "
    "assistant in <= 300 tokens. Preserve concrete facts, decisions, file "
    "paths, error messages, and pending TODOs. Drop greetings and filler. "
    "Output a dense bullet list."
)
SUMMARY_TAG_PREFIX = "[summary v"


@dataclass
class SummariseResult:
    applied: bool
    new_messages: list[dict[str, Any]]
    dropped: int
    summary_chars: int


def needs_summary(
    *,
    estimated_tokens: int,
    ctx_window: int,
    cap_fraction: float = CAP_FRACTION,
) -> bool:
    if ctx_window <= 0:
        return False
    return estimated_tokens > int(ctx_window * cap_fraction)


def is_summary_block(msg: dict[str, Any]) -> bool:
    if msg.get("role") != "system":
        return False
    content = msg.get("content")
    return isinstance(content, str) and content.lstrip().startswith(SUMMARY_TAG_PREFIX)


def _summary_version(msg: dict[str, Any]) -> int:
    content = str(msg.get("content", ""))
    head = content.lstrip()
    # Format: "[summary v3] - bullet ..."
    try:
        end = head.index("]")
        ver = head[len(SUMMARY_TAG_PREFIX) : end]
        return int(ver)
    except (ValueError, IndexError):
        return 1


def _stringify_for_summary(msg: dict[str, Any]) -> str:
    role = msg.get("role", "user")
    content = msg.get("content")
    if isinstance(content, list):
        chunks: list[str] = []
        for c in content:
            if isinstance(c, dict) and isinstance(c.get("text"), str):
                chunks.append(c["text"])
            elif isinstance(c, str):
                chunks.append(c)
        text = "\n".join(chunks)
    elif isinstance(content, str):
        text = content
    else:
        text = ""
    return f"[{role}] {text.strip()}"


def collapse_messages(
    messages: list[dict[str, Any]],
    *,
    summarise: Callable[[str], str] | None,
    keep_tail: int = KEEP_TAIL,
) -> SummariseResult:
    """Collapse old turns into a single summary system block.

    ``summarise(joined_text) -> summary_text`` is provided by the agent so
    we can swap the runtime in tests. When ``summarise is None`` or it
    raises, we fall back to lossy truncation.
    """

    if len(messages) <= keep_tail + 1:
        return SummariseResult(applied=False, new_messages=messages, dropped=0, summary_chars=0)

    # Always keep the very first system message (workspace context, mode
    # addendum). Then look at the "middle" — everything between the head
    # system block and the trailing window — for collapsing.
    head_idx = 0
    if messages and messages[0].get("role") == "system":
        head_idx = 1

    tail_start = len(messages) - keep_tail
    if tail_start <= head_idx:
        return SummariseResult(applied=False, new_messages=messages, dropped=0, summary_chars=0)

    middle = messages[head_idx:tail_start]
    if not middle:
        return SummariseResult(applied=False, new_messages=messages, dropped=0, summary_chars=0)

    # Detect existing summary block to re-roll into a v+1.
    prev_summary: str | None = None
    new_old: list[dict[str, Any]] = []
    prev_version = 0
    for m in middle:
        if is_summary_block(m):
            prev_summary = str(m.get("content", ""))
            prev_version = max(prev_version, _summary_version(m))
        else:
            new_old.append(m)

    # If there's already a summary and no new old messages, nothing to do.
    if prev_summary and not new_old:
        return SummariseResult(applied=False, new_messages=messages, dropped=0, summary_chars=0)

    # Compose the corpus to summarise.
    corpus_parts: list[str] = []
    if prev_summary:
        corpus_parts.append(prev_summary)
    for m in new_old:
        corpus_parts.append(_stringify_for_summary(m))
    corpus = "\n\n".join(corpus_parts)

    # Run the summarisation callback (LLM or stub).
    summary_body: str
    if summarise is not None:
        try:
            summary_body = summarise(corpus).strip() or _truncated_fallback(new_old)
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("summarise() failed: %s", exc)
            summary_body = _truncated_fallback(new_old)
    else:
        summary_body = _truncated_fallback(new_old)

    next_version = prev_version + 1 if prev_version else 1
    summary_text = f"{SUMMARY_TAG_PREFIX}{next_version}] {summary_body}"
    summary_msg = {"role": "system", "content": summary_text}

    new_messages: list[dict[str, Any]] = []
    new_messages.extend(messages[:head_idx])
    new_messages.append(summary_msg)
    new_messages.extend(messages[tail_start:])

    return SummariseResult(
        applied=True,
        new_messages=new_messages,
        dropped=len(middle),
        summary_chars=len(summary_text),
    )


def _truncated_fallback(messages: list[dict[str, Any]]) -> str:
    """Last-resort summary: list each turn's role + first 120 chars."""
    lines: list[str] = []
    for m in messages:
        text = _stringify_for_summary(m).strip().replace("\n", " ")
        if len(text) > 140:
            text = text[:139] + "\u2026"
        lines.append(f"- {text}")
    if not lines:
        return "(no earlier content)"
    return "\n".join(lines)


__all__ = [
    "CAP_FRACTION",
    "KEEP_TAIL",
    "SummariseResult",
    "collapse_messages",
    "is_summary_block",
    "needs_summary",
]
